// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2JLPzfvchppPGSWODIQ4KrzEgYmOk72s',
    appId: '1:186036405046:web:1988b9f1d20a402c80a997',
    messagingSenderId: '186036405046',
    projectId: 'chat-da9a5',
    authDomain: 'chat-da9a5.firebaseapp.com',
    storageBucket: 'chat-da9a5.firebasestorage.app',
    measurementId: 'G-J9SR43BSW9',
    databaseURL: 'https://chat-da9a5-default-rtdb.firebaseio.com', // ✅ Added
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB6kWZm8fF3oYX4IU7LGAmfSra6_nDKf8',
    appId: '1:186036405046:android:b2aee3d4c4743b9a80a997',
    messagingSenderId: '186036405046',
    projectId: 'chat-da9a5',
    storageBucket: 'chat-da9a5.firebasestorage.app',
    databaseURL: 'https://chat-da9a5-default-rtdb.firebaseio.com', // ✅ Added
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7inQHXRGNYCqNj2SitKOJnkW4xfMIslI',
    appId: '1:186036405046:ios:3966597553500fd280a997',
    messagingSenderId: '186036405046',
    projectId: 'chat-da9a5',
    storageBucket: 'chat-da9a5.firebasestorage.app',
    androidClientId: '186036405046-c2pnoghc0kq9pu752a87v052326cspor.apps.googleusercontent.com',
    iosClientId: '186036405046-8fmis31httl3gerps177te3gil4d50uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
    databaseURL: 'https://chat-da9a5-default-rtdb.firebaseio.com', // ✅ Added
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7inQHXRGNYCqNj2SitKOJnkW4xfMIslI',
    appId: '1:186036405046:ios:3966597553500fd280a997',
    messagingSenderId: '186036405046',
    projectId: 'chat-da9a5',
    storageBucket: 'chat-da9a5.firebasestorage.app',
    androidClientId: '186036405046-c2pnoghc0kq9pu752a87v052326cspor.apps.googleusercontent.com',
    iosClientId: '186036405046-8fmis31httl3gerps177te3gil4d50uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
    databaseURL: 'https://chat-da9a5-default-rtdb.firebaseio.com', // ✅ Added
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2JLPzfvchppPGSWODIQ4KrzEgYmOk72s',
    appId: '1:186036405046:web:2c07b89c88b32fcf80a997',
    messagingSenderId: '186036405046',
    projectId: 'chat-da9a5',
    authDomain: 'chat-da9a5.firebaseapp.com',
    storageBucket: 'chat-da9a5.firebasestorage.app',
    measurementId: 'G-Y802F1PR08',
    databaseURL: 'https://chat-da9a5-default-rtdb.firebaseio.com', // ✅ Added
  );
}
